name: Netlify PR Preview

on:
  pull_request:
    types: ['opened', 'edited', 'synchronize']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        docker build -t stage6_se .

    - name: Build Docker image
      run: |
        docker build -t stage6_se .

    - name: Build HTML
      run: |
        mkdir _site
        docker run -v ./_site:/src/_build/html stage6_se

    - name: List site files
      run: |
        ls -all ./_site

    - name: Install the Netlify CLI
      run: npm install netlify-cli -g

    - name: Deploy to Netlify
      run: |
        netlify deploy --dir ./_site --site=${{ secrets.NETLIFY_SITE_ID }} --auth=${{ secrets.NETLIFY_AUTH_TOKEN }} --timeout=600 --message "Deployed on $(date)"
