name: Netlify PR Preview

on:
  pull_request:
    types: ['opened', 'edited', 'synchronize']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        docker build -t stage6_se .

    - name: Build HTML
      run: |
        mkdir /home/runner/work/_temp/_github_home/build
        docker run -v /home/runner/work/_temp/_github_home/build:/src/_build/html stage6_se

    - name: Deploy Netlify
      uses: danakim/gh-action-deploy-netlify@master
      with:
        AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        DEPLOY_PROD: true
