name: PR Tests

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        docker build --build-arg SPHINXOPTS="-W --keep-going -n" -t stage6_se .

    - name: Build HTML
      run: |
        mkdir _site
        docker run -v ./_site:/src/_build/html stage6_se

