name: PR Tests

on:
  pull_request:
    branches:
      - main

jobs:
  pr_tests_build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        docker build -t stage6_se .

    - name: Build HTML
      run: |
        docker run -e SPHINXOPTS="-W -n --keep-going" stage6_se

  pr_tests_lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        docker build -t stage6_se .

    - name: Lint
      run: |
        docker run stage6_se checkfmt
